/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traffic;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Mamun_CSE
 */
public class Traffic extends javax.swing.JFrame {

    /**
     * Creates new form TrafficSignal
     */
    public Traffic() {
        initComponents();
        lblRed.setEnabled(false);
        lblYellow.setEnabled(false);
        lblGreen.setEnabled(false);
       // stop();
    }
    Timer timer;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblGreen = new javax.swing.JLabel();
        lblYellow = new javax.swing.JLabel();
        btnStartt = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        jLabel1.setText("              Traffic Signal ");
        jLabel1.setOpaque(true);

        lblRed.setBackground(new java.awt.Color(0, 0, 0));
        lblRed.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblRed.setForeground(new java.awt.Color(255, 255, 0));
        Toolkit tk =Toolkit.getDefaultToolkit();
        Image img1=tk.getImage(getClass().getResource("/traffic/red.jpg"));
        lblRed.setIcon(new javax.swing.ImageIcon(img1)); // NOI18N
        lblRed.setOpaque(true);

        lblGreen.setBackground(new java.awt.Color(0, 0, 0));
        lblGreen.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        lblGreen.setForeground(new java.awt.Color(255, 255, 102));
       // Toolkit tk =Toolkit.getDefaultToolkit();
        Image img2=tk.getImage(getClass().getResource("/traffic/green.jpg"));
        lblGreen.setIcon(new javax.swing.ImageIcon(img2)); // NOI18N
        lblGreen.setOpaque(true);

        lblYellow.setBackground(new java.awt.Color(0, 0, 0));
        lblYellow.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        lblYellow.setForeground(new java.awt.Color(102, 255, 0));
        Image img3=tk.getImage(getClass().getResource("/traffic/yellow.jpg"));
        lblYellow.setIcon(new javax.swing.ImageIcon(img3)); // NOI18N
        lblYellow.setOpaque(true);

        btnStartt.setBackground(new java.awt.Color(204, 0, 0));
        btnStartt.setFont(new java.awt.Font("Segoe UI Symbol", 2, 24)); // NOI18N
        btnStartt.setText("START");
        btnStartt.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStarttActionPerformed(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(204, 0, 51));
        btnStart.setFont(new java.awt.Font("Segoe UI Symbol", 2, 24)); // NOI18N
        btnStart.setText("STOP");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGreen, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addComponent(lblYellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStartt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRed, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnStartt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStarttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStarttActionPerformed
                
                start();
       
    }//GEN-LAST:event_btnStarttActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
       
        this.setVisible(false);
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traffic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traffic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStartt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGreen;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblYellow;
    // End of variables declaration//GEN-END:variables
    private final int nRed=10;
    private final int nyellow=5;
    private final int nGreen=8;
    int k=nRed;
    int kk=nGreen;
    int kkk = nyellow;
    private void start() {

        int speed=1000;
        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                if(k>=0)
                {
                        lblRed.setEnabled(true);
                        //if(k!=0)
                        lblRed.setText(String.valueOf(k));
                      
                        lblGreen.setEnabled(false);
                        lblYellow.setEnabled(false);
                        if(k==0){
                            lblRed.setText(null);
                        }
                         k--;  
                }     
                else if(kk>=0){
                        lblRed.setEnabled(false);                       
                        lblGreen.setEnabled(true);
                        lblYellow.setEnabled(false);
                        
                        lblGreen.setText(String.valueOf(kk));
                         if(kk==0){
                            lblGreen.setText(null);
                        }
                        kk--;
                        
                        kkk = nyellow;
                
                }    
                else if(kkk>=0)
                {
                    
                        if(kkk==0)
                        {k = nRed;
                        kk=nGreen;
                        lblYellow.setText(null);
                        }
                        lblRed.setEnabled(false);                       
                        lblGreen.setEnabled(false);
                        lblYellow.setEnabled(true);
                        
                        lblYellow.setText(String.valueOf(kkk));
                        
                         if(kkk==0)
                        {
                        lblYellow.setText(null);
                        }
                         kkk--;
                
                }

            }
        };
        
    
        
        timer = new Timer(speed ,action);
        timer.start();
            
    }
}
